# Copyright (c) 2022-2026 Centre National d'Etudes Spatiales (CNES).
#
# This file is part of Bulldozer
# (see https://github.com/CNES/bulldozer).
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

repos:
  
  # Import sorter
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort

  # PEP 8 compliant code formatter
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black

  # Style and syntax errors checker (based on PyFlakes, pycodestyle and McCabe)
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8

  # Type checker
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        exclude: "tests/|setup.py"

  # Static code analyser : checks errors, coding standard and can give code smells
  - repo: https://github.com/pycqa/pylint
    rev: v3.2.0
    hooks:
      - id: pylint
        args: ["--rcfile=.pylintrc"]
        exclude: "tests/|setup.py"
