# Global options:

[mypy]
# Disallows defining functions without type annotations or with incomplete type annotations. For example, it would report an error for def f(a, b) and def f(a: int, b).
disallow_untyped_defs = True

# This flag causes mypy to install known missing stub packages for third-party libraries using pip. For security reasons, these stubs are limited to only a small subset of manually selected packages that have been verified by the typeshed team. These packages include only stub files and no executable code.
install_types = True

# When used together with --install-types, this causes mypy to install all suggested stub packages using pip without asking for confirmation, and then continues to perform type checking using the installed stubs, if some files or modules are provided to type check.
non_interactive = True


# Per package options:

[mypy-scipy]
ignore_missing_imports = true
# with python3.10 consider installing scipy-stubs

[mypy-scipy.*]
ignore_missing_imports = true
# with python3.10 consider installing scipy-stubs

[mypy-rasterio]
ignore_missing_imports = true

[mypy-rasterio.*]
ignore_missing_imports = true

[mypy-Cython.*]
ignore_missing_imports = true

