# Copyright (c) 2022-2026 Centre National d'Etudes Spatiales (CNES).
#
# This file is part of Bulldozer
# (see https://github.com/CNES/bulldozer).
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Global options:

[mypy]
# Disallows defining functions without type annotations or with incomplete type annotations. For example, it would report an error for def f(a, b) and def f(a: int, b).
disallow_untyped_defs = True

# This flag causes mypy to install known missing stub packages for third-party libraries using pip. For security reasons, these stubs are limited to only a small subset of manually selected packages that have been verified by the typeshed team. These packages include only stub files and no executable code.
install_types = True

# When used together with --install-types, this causes mypy to install all suggested stub packages using pip without asking for confirmation, and then continues to perform type checking using the installed stubs, if some files or modules are provided to type check.
non_interactive = True


warn_unused_ignores = True
warn_redundant_casts = True
warn_unreachable = True
no_implicit_optional = True

# Check specifically numpy typing
plugins = numpy.typing.mypy_plugin

# Per package options:
[mypy-scipy.*]
ignore_missing_imports = true

[mypy-rasterio.*]
ignore_missing_imports = true

[mypy-Cython.*]
ignore_missing_imports = true