#-------------------------#
#       Parameters        #
#-------------------------#
# [Required] - Input DSM path (expected format: "<folder_1>/<folder_2>/<file>.<[tif/tiff]>") 
dsm_path : "input_dsm_path/dsm.tif"
# [Required] - Output directory path (if the directory doesn't exist, create it)
output_dir : "output_dir_path"

#-------------------------#
#         Options         #
#-------------------------#
# [Optional] - If True, generates the DHM (DSM - DTM) in the output directory 
generate_dhm : True
# [Optional] - Number of workers. If null, use maximum number of available CPU core 
nb_max_workers : 8
# [Optional] - Foreground max object size (in meter)
max_object_size : 16

#-------------------------#
#    Advanced settings    #
#-------------------------#
# [Optional] - Altimetric height accuracy of the input DSM (m). If null, use the default value: 2*planimetric resolution
dsm_z_accuracy: null
# [Optional] - Maximum slope of the observed landscape terrain (%)
max_ground_slope: 20.0
# [Optional] - If True, activate the ground pre-detection
activate_ground_anchors : False
# [Optional] - If True, keep the intermediate results
developer_mode : False
# [Optional] - Binary ground mask path (expected format: "<folder_1>/<folder_2>/<mask>.<[tif/tiff]>") 
ground_mask_path : null

#-------------------------#
# Bulldozer core settings #
#-------------------------#
# /!\ Modify those data at your own risk (it is suggested to keep the default values) /!\

# [Optional] - DtmExtraction parameters
cloth_tension_force : 3
prevent_unhook_iter : 10
num_outer_iter : 25
num_inner_iter : 5