#-------------------------#
#       Parameters        #
#-------------------------#
# Input DSM path (expected format: "<folder_1>/<folder_2>/<file>.<[tif/tiff]>")
# "/work/OT/ai4geo/users/benchmark/DTM/IN_BENCHMARK/MNS_Toulouse.tif"
dsmPath : "/work/OT/ai4geo/users/benchmark/DTM/IN_BENCHMARK/MNS_Nice.tif"
# Output directory path
outputDir : "/work/scratch/lassalp/AI4GEO_WORKSPACE/ai4geo_toolbox_output/"
# If null, bulldozer will use the maximum number of available workers on your system (warning: check the README if you're using bulldozer on cluster) 
nbMaxWorkers : 24

#-------------------------#
#         Options         #
#-------------------------#
# If True, generates the DHM (DSM - DTM) in the output directory 
dhm : True
# If True, generates the filled MNS : MNS without inner noData or disturbed areas
createFilledDsm : True
# If True, generates a logfile in the output directory
keepLog : True

#-------------------------#
#    Advanced settings    #
#-------------------------#
# If null, the output DTM CRS will be the same as the input CRS. 
# Expected PROJ parameters (e.g: 'epsg:3005') or EPSG codes (e.g: 3005). FYI : WGS84 is analogous to EPSG:4326
outputCRS : null
# If null, the output DTM resolution will be the same as the input DSM (float value in meter)
outputResolution : null
# If null, the DSM resolution will be extracted from the input DSM (float value in meter)
dsmResolution : null
# If null, the nodata value will be extracted from the input DSM (float value or nan)
noData : null


#-------------------------#
# Bulldozer core settings #
#-------------------------#
# /!\ Modify those data at your own risk (it is suggested to keep the default values) /!\

# DetectDisturbedAreasAndFill part
slopeThreshold : 2.0
# numnumber of evaluated axis. Vertical and horizontal if true else vertical, horizontal and diagonals.
fourConnexity : True

# DtmExtraction part
# max object width in meter
maxObjectWidth : 24
uniformFilterSize : 1
preventUnhookIter : 10
numOuterIter : 100
numInnerIter : 10
mpTileSize : 1500
sequential : False