#-------------------------#
#       Parameters        #
#-------------------------#
# Input DSM path 
DSMPath : "/work/scratch/lallemd/bulldozer/rtdrapcloth/test/cropped_Tlse_MNS.tif"
# Output directory
outputDir : "/work/scratch/lallemd/tmp/"
# If null, bulldozer will use the maximum number of available workers on your system (warning: check the README if you're using bulldozer on cluster) 
nbMaxWorkers : 16

#-------------------------#
#         Options         #
#-------------------------#
# If True, generates the DHM (DSM - DTM) in the output directory 
DHM : True
# If True, generates a logfile in the output directory
keepLog : True
# If True, generates the filled MNS (MNS without noData but still with disturbed areas)
keepFilledDSM : True
# If True, generates the corrected MNS (MNS without noData and without disturbed areas)
keepCorrectedDSM : True

#-------------------------#
#    Advanced settings    #
#-------------------------#
# If null, the output DTM CRS will be the same as the input CRS (float value in meter)
outputCRS : null
# If null, the output DTM resolution will be the same as the input DSM (float value in meter)
outputResolution : null
# If null, the nodata value will be extracted from the input DSM (float value in meter)
nodata : null
# If null, the DSM resolution will be extracted from the input DSM (float value in meter)
DSMResolution : null

#-------------------------#
# Bulldozer core settings #
#-------------------------#
# /!\ Modify those data at your own risk (it is suggested to keep the default values) /!\

# FillNoData part
# max search distance in meter
maxSearchDistance : 100.0
smoothingIterations : 0
newValue : nan

# DetectDisturbedAreasAndFill part
slopeThreshold : 2.0
disturbedThreshold : 3
disturbedInfluenceDistance : 5.0

# DtmExtraction part
# max object width in meter
maxObjectWidth : 100.0
numInnerIterationsStep1: 10
numOuterIterationsStep2: 100
numInnerIterationsStep2: 10
