#-------------------------#
#       File paths        #
#-------------------------#
# Input DSM path 
dsmPath : "/work/OT/ai4geo/DATA/PROCESSED/MNS/PHR/Toulouse/mergedDSM.tif"
# Output path for the filled DSM (DSM without noData)
outputFillDsmPath : "/work/scratch/lassallep/filled_dsm.tif"
# Output path for the corrected DSM (DSM without noData & without disturbed area)
outputCorrectedDsmPath : "/work/scratch/lassallep/tmp/corrected_dsm.tif"
# Output DTM path 
outputDtmPath : "/work/scratch/lassallep/dtm.tif"

#-------------------------#
# Input image information #
#-------------------------#
nodata : -32768.0
dsmResolution : 0.5

#-------------------------#
#    Advanced settings    #
#-------------------------#
# if True, generates a logfile in the output directory
keepLog : False

# /!\ Modify those data at your own risk (it is suggested to keep the default values) /!\

# FillNoData part
# max search distance in meter
maxSearchDistance : 100.0
smoothingIterations : 0
new_value : nan

# DetectDisturbedAreasAndFill part
slopeThreshold : 2.0
disturbedThreshold : 3
disturbedInfluenceDistance : 5.0

# DtmExtractionWithCNESStrategy part
# max object width in meter
maxObjectWidth : 100.0
numInnerIterationsStep1: 10
numOuterIterationsStep2: 100
numInnerIterationsStep2: 10
